config_test: add a failing test to showcase that uploader_id missing
I found that, in venafi cloud key pair service account mode, the
arbitrary path segment "/no" was now missing due to my refactoring. This
commit adds a unit test to show this.

Test result:

--- FAIL: Test_ValidateAndCombineConfig_VenafiCloudKeyPair (0.00s)
    --- FAIL: Test_ValidateAndCombineConfig_VenafiCloudKeyPair/server,_uploader_id,_and_cluster_name_are_correctly_passed (0.00s)
        envtest.go:188: fake api.venafi.cloud received request: POST /v1/oauth/token/serviceaccount
        envtest.go:188: fake api.venafi.cloud received request: POST /v1/tlspk/upload/clusterdata
        config_test.go:586:
                Error:          Not equal:
                                expected: "/v1/tlspk/upload/clusterdata/no"
                                actual  : "/v1/tlspk/upload/clusterdata"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -/v1/tlspk/upload/clusterdata/no
                                +/v1/tlspk/upload/clusterdata
                Test:           Test_ValidateAndCombineConfig_VenafiCloudKeyPair/server,_uploader_id,_and_cluster_name_are_correctly_passed