[VC-48429] helm chart updates
Enables secret sending by default when ToS is accepted.

Also adds acceptTerms validation, which causes the chart to error out if
the value is not set.

The error looks like this:

```console
$ helm template foo ./deploy/charts/disco-agent
Error: execution error at (disco-agent/templates/deployment.yaml:2:6):

=================================================================
                Terms & Conditions Notice
=================================================================

Before installing this application, you must review and accept
the terms and conditions available at:
https://www.cyberark.com/contract-terms/

To proceed with installation, you must indicate acceptance by
setting:

  - In your values file: acceptTerms: true
  or
  - Via the Helm flag: --set acceptTerms=true

By continuing with the next command, you confirm that you have
reviewed and accepted these terms and conditions.

=================================================================
```

Signed-off-by: Ashley Davis <ashley.davis@cyberark.com>